gardener/website-generator

hugo/layouts/partials/git_author.html, hugo/layouts/partials/git_avatar.html, hugo/layouts/partials/git_date.html
The website build uses git commits info to set author, avatar and publish date e.g. in blogs or tutorials automatically. This change adds the ability to override this mechanism with corresponding front-matte properties: `author`, `avatar` and `publishdate`. If any of these is specified it takes priority over the commits info.
=> github commits autor,avatar,date can be now overriden in front-matter

.ci/build
Unauthenticated requests from the nodejs pre-build script to the github.com API quickly hit the rate limit (60 per hour). To avoid this, a github user frоm the CI config will be used during CI builds.
=> Use ci user github config for authenticated requests

.ci/build, Dockerfile, Makefile, scripts/image-build, scripts/image-push
The build now requires `gardener-ci`, which is part of the cc/job-image so we use it as basis and node/npm are added now as alpine package dependency. An unfortunate side effect is that the image size grew significantly up to 850MB. Future improvement steps would be to move to alpine as basis and copy only the minimal dependencies from cc/job-image.
=> based on cc-jobimage,switched to semver

hugo/assets/sass/_blog.scss, hugo/layouts/blog/list.html, hugo/layouts/blog/single.html, hugo/layouts/partials/blog-authors.html, hugo/layouts/partials/git_author.html, hugo/layouts/partials/git_avatar.html, hugo/layouts/partials/git_date.html, hugo/layouts/partials/tail-scripts.html, node/index.js, package-lock.json, package.json
Tailored git info supporting site building in layouts that need authors, contributors and their details (names, avatars,emails), lastmodified/publish dates. Previously, it was serialized as raw commits history per file in the content repository (/documentation) and was unnecessarily served online along the actual site content. Now git info is serialized in the hugo/data folder, which is meant by hugo precisely for this purpose and is not exposed as site content too. As the git info is tailored specifically for our use case now, the layouts using it now require less transformations to make use of it too.
Blogs now support multiple authors too.
The partials working with gitinfo first check the page for 
```yaml
authors:
- name: ""
email: ""
avatar: "" …
```
=> moved git info to hugo/data

hugo/layouts/partials/head-docs.html, hugo/layouts/partials/header_blank.html, hugo/layouts/partials/header_remote.html
Introduces the correct way to generate pages that link gardener.css in several layouts that failed to do that and could not load it.
=> Fix usage of gardener.css in layouts

hugo/assets/sass/_base.scss, hugo/assets/sass/_blog.scss, hugo/assets/sass/_news-feed.scss, hugo/assets/sass/_news.scss, hugo/layouts/blog/blog-list.html, hugo/layouts/blog/list.html, hugo/layouts/news/list.html, hugo/layouts/news/single.html, hugo/layouts/partials/footer.html, hugo/layouts/partials/news.html
With this PR the following improvements are introduced:
- The news feed on the landing page now includes also blogs. Blog news feed items that appear there are links directly to the respective blog in the Blogs section. You no longer need to publish a separate _News_ content to announce a blog on the news feed.
- News are preserved as distinct content type, but will be largely used for _inline_ short notices for now on. Such notices will appear in a lightbox container as up to now. They will continue to be available for exploration in the news section.
- Scheduling of news now includes also publish date, i.e. if there is a `publishdate` property in the front-matter, it will be considered when deciding whether to show this news item in the feed on …
=> News and blogs

hugo/assets/sass/_blog-home.scss, hugo/assets/sass/_blog.scss, hugo/layouts/blog/blog-list.html, hugo/layouts/partials/blog-authors.html
The blogs section used to be listing directly all blogs content. This PR introduces actual blogs home page with basic exploratory functions: 
- filter list by blogs title or annotation
- blogs link shortcuts grouped by Month-Year
The short annotations in the list are rendered from the blogs front matter description (if exists) or its content, truncated intelligently (considering the html) up to 200 rendered symbols. Tags such as images, objects or tables are hidden to be able to make use of the content for that purpose. It is preferable and recommended to use the description and only fallback to the content to derive short annotation for the blog list only for legacy content.
Added estimated reading time (function from Hugo).
The By-Time navigation …
=> Blogs home page

hugo/assets/sass/_blog-home.scss, hugo/layouts/blog/blog-list.html, hugo/layouts/shortcodes/blog_img.html
Blogs can be tagged now using front matter property `tags`. Tags will appear with each list item in the home page. Only the first 5 are considered.
=> Blogs tag support

.ci/gitlog.sh, node/index.js
Restructuring documentation lead to loss of git-related info intended to be shown on the documentation pages  - committers most notably. The reason is, that the current method for gathering such git info is via getting files commit history from GitHub API and it doesn't support history across rename or move operations on a file (unlike `git log --follow`).
This PR introduces a new method to get git info that uses the GitHub API more sparingly and relies on information from `git log` for local files where applicable. The `git log` output is missing GitHub related details (e.g. usernames and avatar urls) and it is complemented with additional contributors info from GitHub, as necessary.
The node script that fetches git commits changed to invoke a …
=> Preserve git info and history across renames/moves

.ci/gitlog.sh, node/index.js, package-lock.json, package.json
Fixes an issue with failure to get contributors for a local source with git log, due to file argument path format.
Fixes gardener/documentation#116
=> Fix no contributors due to git log failing to execute

Dockerfile
Sets eu.gcr.io/gardener-project/cc/job-image:1.816.0 Docker image as base to website-generator Dockerfile
It sets the cc/job-image to newer version 1.816.0
Fixes #
website-generator image had an issue, where it couldn't reach github.com from the container
```improvement operator
website-generator Docker image uses eu.gcr.io/gardener-project/cc/job-image:1.816.0 as base
```
=> update job-image to 1.816.0 image version

Dockerfile
- change alpine base image registry to gcr to prevent hitting pulls quota
- upgrade docforge to apply latest fixes
=> Change image registry, upgrade docforge

Dockerfile
upgrade hugo and docforge in gardener-website-generator image to meet the requirements for the latest layouts
```improvement operator
NONE
```
=> Upgrade hugo and docforge in gardener-website-generator image

.ci/build
Add local build ENV var. In this way there will be separation between CI/CD Build and Local build
Fixes #
```improvement operator
LOCAL_BUILD env var is added. If it is set to true, then there will not be installed npm packages
```
=> Add local build ENV var

hugo/layouts/docs/list.html
Remove description from the docs pages layout because usually it duplicates the first Header
Fixes #
```improvement operator
None
```
=> Remove description from the docs pages layout

Makefile, scripts/image-stable
Make image-stable step is added in the Makefile
Fixes #
```improvement operator
make image-stable step is added in the Makefile
```
=> Add make-image-stable step in the Makefile

.ci/pipeline_definitions
Fixes #
Enables HUGO mermaid & emoji in 10.26.0
```improvement operator
Enable Mermaid diagrams and GitHub emoji in HUGO configuration 
```
=> Update gardener-website-generator image to 10.26.0

.ci/pipeline_definitions
Update gardener-website-generator image to 10.27.0
Fixes #
```improvement operator
None
```
=> Update gardener-website-generator image to 10.27.0

.ci/pipeline_definitions, Dockerfile
Use docforge:v0.29.0 & gardener-website-generator:10.32.0 images
Updates HUGO to v.0.95.0
Fixes #
```noteworthy developer
Updates HUGO to v.0.95.0
```
=> Use docforge:v0.29.0 & gardener-website-generator:10.32.0 images

scripts/image-build
Removing workaround in image_build.sh for issue https://github.com/dotcloud/docker/issues/1875
```improvement developer
Removing workaround in image_build.sh for docker build issue
```
=> Removing docker build issue workaround

hugo/layouts/partials/sidebar-tree.html
Fix sidebar content cut
```improvement operator
NONE
```
=> Fix sidebar content cut

.ci/404.sh, hugo/layouts/404.html
This PR updates the layout of the "404 Page Not Found" page:
- reworked the displayed text
- decreased the size of the title
- increased the size of the links
- added spacing between links
- aligned the bullet points to the left in a centered div
- added code to place an image (currently as a comment; image TBD)
Fixes #212 
```improvement developer
NONE
```
=> Updated "404 Page Not Found" page layout

.ci/404.sh
This PR fixes links not being shown in the "Page Not Found" error page.
Fixes #
```improvement developer
NONE
```
=> Fixed links in Page Not Found page

hugo/layouts/partials/navbar.html
Adding a dropdown menu for increased visibility of persona filtering.
Fixes #
```improvement operator
NONE
```
=> Dropdown menu for filtering content per persona

hugo/layouts/index.html
Fixes the page redirection on first click of Documentation dropdown menu
```improvement operator
On first click on the Documentation dropdown menu, it will now redirect you to the correct persona filtered page.
```
=> Fix redirection on first click of Documentation

hugo/layouts/_default/_markup/render-blockquote-alert.html, hugo/layouts/_default/_markup/render-blockquote-regular.html, hugo/layouts/partials/navbar.html
Beautify the look of notes parsed from .md files
Fixes #222 
N/A
```improvement operator
The website now supports the `[!(NOTE|IMPORTANT|TIP|WARNING|CAUTION)]` syntax
```
=> Add support for Github notes syntax

Dockerfile, compose.yaml
This PR moves the setting of the environment variable `DOCFORGE_CONFIG` to be done from the `compose.yaml` file to allow supporting the ci/cd scenario
```improvement operator
NONE
```
=> [Docker] Move `DOCFORGE_CONFIG` in compose instead of image

Dockerfile
The image build from `Dockerfile` will contain `docsy@DOCSY_VERSION` under `hugo/themes`
```improvement operator
NONE
```
=> [Docker] Setup `docsy@DOCSY_VERSION` under `hugo/themes` on image build

Dockerfile
This PR adds the ability to build the website and put it's content into the folder `BUILD_DESTINATION` if that environment variable is set
```improvement operator
NONE
```
=> [Docker] Add `BUILD_DESTINATION`

Dockerfile
This PR adds `DOCFORGE_CONFIG_PATH` environment variable to `Dockerfile` that lets docforge use `DOCFORGE_CONFIG_PATH/config` as configuration. If path is relative it will be resolved relative to the container's root
```improvement operator
NONE
```
=> [Docker] Add `DOCFORGE_CONFIG_PATH`

README.md
This PR adds the steps explaining how to develop locally
Part of https://github.com/gardener/website-generator/issues/238
```improvement operator
NONE
```
=> [Docker] support local dev

Dockerfile
```improvement operator
NONE
```
=> Dockerfile uses docforge v0.50

hugo/config.toml
```improvement operator
NONE
```
=> Diasbe unnessesary `enableGitInfo`

hugo/layouts/docs/list.html
Reverts the removal of grouping of articles in docs index page.
N/A
N/A
```improvement operator
NONE
```
=> Revert removal of docs/list.html layout

hugo/static/js/resizable-sidebar.js
A dirty fix for the mobile version of the website where the sidebars are already unusable and don't show anything, but they limit the main content's size. Introduces a check for mobile devices.
N/A
A temporary fix for current ongoing events and better promoting using the website.
```improvement operator
NONE
```
=> Clean up sidebars hiding main content on mobile devices

hugo/assets/sass/_base.scss, hugo/layouts/community/baseof.html
Improves format of https://github.com/gardener/documentation/pull/598, so that it could be ready for review.
Fixes #282 
Needed for https://github.com/gardener/documentation/pull/598 to be merged.
```improvement operator
NONE
```
=> Community Page Review Meetings Enhancement

hugo/layouts/partials/footer.html
/kind enhancement
/area open-source
This PR switches all Slack references to the dedicated Gardener Project workspace.
Part of https://github.com/gardener/documentation/issues/606
```improvement operator
NONE
```
=> Switch Slack references to Gardener workspace
