gardener/website-generator

- hugo/layouts/partials/toolbar.html
- hugo/static/css/main.css
Fixes gardener/documentation#69.
> Prevent adblock to hide the nav bar

- hugo/layouts/partials/head-google-tag-manager.html
Changed google analytics account and need to update the corresponding tracking id.
> Change site tracking-id

- hugo/layouts/blog/list.html
- hugo/layouts/partials/git_date.html
- hugo/layouts/partials/head.html
- hugo/layouts/partials/tail-scripts.html
- hugo/layouts/partials/tln.html
- Blog dates fixed 
- reconciled the various input formats from front matter and git)
- previously only the first entry form git commits was considered and if it was not eligible for showing, no date was produced. Now the partial iterates until an eligible entry is found.
- JS script fixes:
- import ordered according to dependencies
- JS scripts reduced
- use of moment.js optimized
- Sticky TLN fixed: now the sticky point is correctly calculated and applied for non-landing pages too.
> Blogs fixes

- hugo/layouts/partials/footer.html
@gardener/gardener-maintainers
> fix typo in footer

- hugo/layouts/shortcodes/blog_img.html
Resolves relative paths correctly. 
Move on to using named parameters instead of positional.
> Improved blog_img shortcode

- .ci/build
- .ci/pipeline_definitions
- Dockerfile
- hugo/layouts/docs/list.html
- hugo/layouts/docs/single.html
- node/index.js
Fixes gardener/documentation#116
Fixes gardener/documentation#124
> fix gitlog issue missing perl, fix go fail hugo

- .ci/build
- Dockerfile
Use remote template when building the website.
> use remote template

- .ci/build
Fixes #
```improvement operator
```
> use rrobin fr github auth

- .ci/pipeline_definitions
Switch to a new docforge.
This PR is needed for Docsy theme.
Fixes #
```improvement operator
Update docforge version to 0.11.0
```
> [Docsy] Release new docforge

- .ci/pipeline_definitions
Release website-generator
Fixes #
```improvement operator
None
```
> Release website-generator

- .ci/build
- Dockerfile
Fixes #
Install postcss-cli
```improvement operator
None
```
> Install postcss-cli

- hugo/assets/sass/_landing-page.scss
- hugo/assets/sass/_news-feed.scss
- hugo/assets/sass/gardener.scss
- hugo/assets/scss/_blog-doc.scss
- hugo/assets/scss/_custom-search.scss
- hugo/layouts/index.html
- hugo/layouts/partials/navbar.html
Fix landing page when size is lower than 750px
Fixes #
```improvement operator
None
```
> Fix landing page when size is lower than 750px

- hugo/assets/sass/_landing-page.scss
- hugo/assets/scss/_blog-doc.scss
Change min-size constants in the landing page
Now they follow the landing page resizing approach:
```
@media (min-width: 576px) 
@media (min-width: 768px) 
@media (min-width: 992px) 
@media (min-width: 1200px) 
```
Fixes #
```improvement operator
None
```
> Change min-size constants in the landing page

- hugo/assets/sass/_landing-page.scss
- hugo/assets/sass/_news-feed.scss
- hugo/assets/sass/gardener.scss
- hugo/assets/scss/_custom-grid.scss
- hugo/assets/scss/_styles_project.scss
- hugo/layouts/index.html
- hugo/layouts/partials/news.html
Fix news section
Fixes #
```improvement operator
None
```
> Fix news section

- hugo/assets/sass/_community.scss
- hugo/assets/scss/_adopter.scss
Fix community and adopters page on low resolution screens
Fixes #
```improvement operator
None
```
> Fix community and adopters page on low resolution screens

- hugo/assets/sass/_community.scss
- hugo/assets/scss/_blog-doc.scss
Add some padding in community page.
Remove RSS button on phone screens
Fixes #
```improvement operator
None
```
> Add some padding in community page

- hugo/layouts/community/list.html
Update Community Meetings button to open a new url
Fixes #
```improvement user
NONE
```
> Update Community Meetings button

- .ci/pipeline_definitions
- Dockerfile
Use docforge:v0.12.0 & gardener-website-generator:10.13.0 images
Fixes #
```improvement operator
```
> use gardener-website-generator:10.13.0

- .ci/build
- .ci/pipeline_definitions
- Dockerfile
Git handler witch a cache will be used for docforge building.
Fixes #
```improvement operator
the github handler has been replaced by a git handler
```
> Release: use git handler

- .ci/build
Add debug string in build command
Fixes #
```improvement operator
None
```
> Add debug string in build command

- .ci/build
Fix git issue
Fixes #
```improvement operator
None
```
> Fix git issue

- .ci/build
Fixes for git
Fixes #
```improvement operator
None
```
> Fixes for git

- .ci/build
Fixes for git handler
Fixes #
```improvement operator
None
```
> Fixes for git handler

- .ci/build
Remove debug messages
Fixes #
```improvement operator
None
```
> Remove debug messages

- .ci/pipeline_definitions
Update cache dir
Fixes #
```improvement operator
None
```
> Update cache dir

- .ci/build
Check if cache exists
Fixes #
```improvement operator
None
```
> Check if cache exists

- .ci/build
Reverts gardener/website-generator#104
> Revert "Check if cache exists"

- .ci/build
Install npm modules only if they are missing
Fixes #
```improvement operator
None
```
> Install npm modules only if they are missing

- .ci/build
Fix modules installation
Fixes #
```improvement operator
None
```
> Fix modules installation

- .ci/build
Add npm audit fix for fixing dependencies issues
Fixes #
```improvement operator
None
```
> Add npm audit fix

- .ci/build
Remove unnecessary packages
Fixes #
```improvement operator
None
```
> Remove unnecessary packages

- .ci/build
Revert Running npm audit fix
Fixes #
```improvement operator
None
```
> Revert Running npm audit fix

- Dockerfile
Install node through apk
Fixes #
@dimitar-kostadinov 
```improvement operator
None
```
> Install node through apk

- README.md
This PR adds new tutorials to the documentation for the external website.
```improvement developer
NONE
```
> Added tutorials to README

- .ci/build
Add org in the docforge command
Fixes #
```improvement operator
None
```
> Add org in the docforge command

- .ci/build
- .ci/pipeline_definitions
- Dockerfile
Release website-generator and switch back to Git handler
Fixes #
```improvement operator
None
```
> Release website-generator and switch back to Git handler

- .ci/pipeline_definitions
- Dockerfile
Release with docforge 1.19
Fixes #
```improvement operator
None
```
> Release with docforge 1.19

- .ci/pipeline_definitions
- Dockerfile
Release website-generator with docforge 0.20
Fixes #
```improvement operator
None
```
> Release website-generator with docforge 0.20

- .ci/pipeline_definitions
- Dockerfile
Release with docforge 0.21
Fixes #
```improvement operator
None
```
> Release with docforge 0.21

- .ci/pipeline_definitions
- Dockerfile
Use docforge:v0.22.0 & gardener-website-generator:10.23.0 images
Fixes #
```improvement operator
None
```
> Use docforge:v0.22.0 & gardener-website-generator:10.23.0 images

- hugo/assets/sass/_base.scss
Reset ordered and unordered lists to default settings
Fixes #
```noteworthy user
Reset ordered and unordered lists to default settings
```
> Reset ordered and unordered lists to default settings

- .ci/pipeline_definitions
- Dockerfile
Use docforge:v0.24.0 & gardener-website-generator:10.25.0 images
Fixes #
```improvement operator
None
```
> Use docforge:v0.24.0 & gardener-website-generator:10.25.0 images

- hugo/config.toml
Enable HUGO mermaid & emoji
Fixes #
```improvement user
Enable Mermaid diagrams and GitHub emoji in HUGO configuration 
```
> Enable HUGO mermaid & emoji

- hugo/assets/sass/_code-snippets.scss
- hugo/config.toml
Configure mermaid forest theme
Fixes #
```improvement user
Pre-configured forest theme for mermaid diagrams is available: 
https://www.docsy.dev/docs/adding-content/diagrams-and-formulae/#diagrams-with-mermaid
```
> Configure mermaid forest theme

- .ci/pipeline_definitions
- Dockerfile
Use docforge:v0.25.0 & gardener-website-generator:10.28.0 images
Fixes #
```improvement operator
None
```
> Use docforge:v0.25.0 & gardener-website-generator:10.28.0 images

- .ci/build
Set docforge --cache-dir option
Fixes #
```improvement operator
None
```
> Set docforge --cache-dir option

- .ci/pipeline_definitions
- Dockerfile
Use docforge:v0.26.0 & gardener-website-generator:10.29.0 images
Fixes #
```improvement operator
None
```
> Use docforge:v0.26.0 & gardener-website-generator:10.29.0 images

- .ci/pipeline_definitions
- Dockerfile
Use docforge:v0.27.0 & gardener-website-generator:10.30.0 images
Fixes #
```improvement operator
None
```
> Use docforge:v0.27.0 & gardener-website-generator:10.30.0 images

- .ci/pipeline_definitions
- Dockerfile
Use docforge:v0.28.0 & gardener-website-generator:10.31.0 images
Fixes #
```improvement operator
None
```
> Use docforge:v0.28.0 & gardener-website-generator:10.31.0 images

- README.md
Make the Local build steps up to date
Fixes #
```improvement operator
None
```
> Make the Local build steps up to date

- README.md
Change the link from internal to external
Fixes #
```improvement operator
None
```
> Change the link from internal to external

- README.md
Fix Github link
Fixes #
```improvement operator
None
```
> Fix Github link

- .ci/pipeline_definitions
- Dockerfile
Uses docforge:v0.30.0 & gardener-website-generator:10.33.0 images
Fixes #
```improvement operator
None
```
> Use docforge:v0.30.0 & gardener-website-generator:10.33.0 images

- .ci/pipeline_definitions
- Dockerfile
Release website generator with docforge 0.31.0
Fixes #
```improvement operator
None
```
> Release website generator with docforge 0.31.0

- .gitmodules
- hugo/config.toml
- hugo/layouts/partials/section-index.html
- hugo/layouts/partials/toc.html
Update docsy theme with the main branch of docsy
Fixes #
```improvement user
Docsy theme was updated
```
> Update docsy theme with the main branch of docsy

- hugo/config.toml
Enables google analytics 
```improvement developer
Google analytics enabling
```
> Google analytics enabling

- hugo/layouts/partials/docs/page-meta-links.html
Auto url in issue body
```improvement developer
Auto url in issue body
```
> Auto url in issue body

- hugo/layouts/partials/news.html
News redirect and don't open new window
```improvement developer
News redirect and don't open new window
```
> News redirect

- .ci/build
- .ci/pipeline_definitions
Build script refactoring
```improvement developer
Build script refactoring
```
> Build script refactoring

- hugo/layouts/partials/news.html
News upper limit
```improvement developer
News upper limit
```
> News upper limit

- hugo/layouts/community/list.html
Community table fix
```improvement develoer
Community table fix
```
> Community table fix

- hugo/layouts/blog/list.html
- hugo/layouts/partials/sidebar-tree.html
Showing only unarchived blogs
```improvement developer
Show only unarchived blogs
```
> Showing only unarchived blogs

- .ci/pipeline_definitions
- Dockerfile
Uses docforge:v0.32.0 & gardener-website-generator:10.35.0 images
Fixes #
```improvement operator
NONE
```
> Use docforge:v0.32.0 & gardener-website-generator:10.35.0 images

- hugo/layouts/blog/baseof.html
- hugo/layouts/docs/baseof.html
- hugo/static/css/resizable-sidebar.css
- hugo/static/js/resizable-sidebar.js
Add sidebar resizing
```improvement developer
Added sidebar resizing
```
> Add sidebar resizing

- hugo/layouts/blog/baseof.html
- hugo/layouts/docs/baseof.html
- hugo/static/css/resizable-sidebar.css
Minor resizing fix
```improvement developer
NONE
```
> Minor resizing fix

- hugo/layouts/blog/baseof.html
- hugo/layouts/docs/baseof.html
Replace lorem ispum with repeated one character
```improvement developer
NONE
```
> Second minor resizing change

- hugo/config.toml
Added Gardener logo as a thumbnail image for social media
Fixes #
```improvement operator
NONE
```
> Add a thumbnail image for social media

- .ci/pipeline_definitions
- Dockerfile
Update docforge to v0.34
```improvement developer
Update docforge to v0.34
```
> Update docforge to v0.34

- .ci/build
- .ci/pipeline_definitions
- Dockerfile
Update to use latest docforge
```improvement develoer
NONE
```
> Updating docforge 35

- hugo/config.toml
This PR reorders the sections in the navigation bar.
Fixes #
```improvement developer
NONE
```
> Reordered navigation bar

- README.md
This PR updates the Local Setup steps outlined in the README.md.
Fixes #
```improvement developer
NONE
```
> Removed outdated commands

- .ci/pipeline_definitions
- Dockerfile
- hugo/config.toml
- hugo/layouts/partials/category_map.html
- Use newer docforge
- Handle personas
```improvement operator
NONE
```
> Use personas

- .ci/pipeline_definitions
- Dockerfile
Use latest docforge
```improvement operator
NONE
```
> Use latest docforge

- .ci/pipeline_definitions
Add email notifications
```improvement operator
NONE
```
> Add email notifications

- .ci/pipeline_definitions
- Dockerfile
Update to v42
```improvement operator
NONE
```
> Update to v42

- hugo/config.toml
Fixes https://github.com/gardener/website-generator/issues/194
```improvement operator
NONE
```
> Disable project issues

- .ci/build
Tmp adopters fix
```improvement developer
NONE
```
> Tmp adopters fix

- .ci/build
Add missing -i flag
```improvement developer
NONE
```
> Add missing -i flag

- .ci/build
- .ci/pipeline_definitions
- Dockerfile
- Makefile
- scripts/release
Use docforge v0.43
```improvement developer
NONE
```
> Use docforge v0.43

- hugo/config.toml
- hugo/layouts/index.html
This PR updates the public Landing page links and hides the blogs.
Fixes #
```improvement developer
NONE
```
> Updated the Landing Page - Part 1

- hugo/config.toml
disableAssetsBusting should be in [params] section
```improvement developer
NONE
```
> disableAssetsBusting should be in [params] section

- .ci/pipeline_definitions
- Dockerfile
Fixes #
```improvement developer
NONE
```
> Use docforge v0.44

- .ci/build
- hugo/assets/js/anchor.js
Fix anchor and empty commit build failure
```improvement operator
NONE
```
> Fix anchor and empty commit build failure

- .ci/pipeline_definitions
- Dockerfile
Fixes #
```improvement operator
NONE
```
> Use docforge v0.45

- .ci/build
This PR adds special handling in build script to diki hardened-shoot report documentation files.
Fixes #
```improvement operator
NONE
```
> Add special handling for diki report docu in build script

- .ci/build
This PR fixes style collisions in diki report page
Fixes #
```improvement operator
NONE
```
> Fix diki hardened-shoot report docu styles

- .ci/build
- .ci/pipeline_definitions
- Dockerfile
- Makefile
Fixes #
```improvement operator
NONE
```
> Use docforge v0.46

- .ci/pipeline_definitions
- Dockerfile
- Makefile
- scripts/image-build
- scripts/image-push
- scripts/image-stable
Fixes #
```improvement operator
```
> Migrate remaining GCR occurrences to GAR

- hugo/layouts/index.html
This PR:
- updates the text of the landing page sections
Fixes #
Part of https://github.com/gardener/website-generator/issues/203
```improvement developer
NONE
```
> Landing Page Update - Part 2

- .ci/pipeline_definitions
Fixes #
```improvement operator
NONE
```
> Simplify pipeline_definitions

- hugo/assets/scss/_selected-taxonomy.scss
- hugo/layouts/partials/docs/page-meta-links.html
- hugo/layouts/partials/navbar.html
- hugo/static/js/persona-filtering.js
Fixes #
```improvement operator
NONE
```
> Moving side indexes to a dropdown menu in the Documentation section

- .ci/pipeline_definitions
- scripts/image-build
N/A
N/A
N/A
```improvement operator
NONE
```
> Add and support for website image

- .ci/build
N/A
N/A
N/A
```improvement operator
NONE
```
> Update npm install directory

- .ci/build
N/A
N/A
N/A
```improvement operator
NONE
```
> Add npm install in Hugo directory

- hugo/assets/sass/_landing-page.scss
Fixes #
```improvement operator
NONE
```
> Fix landing page

- README.md
- hugo/assets/sass/_base.scss
- hugo/layouts/_default/_markup/render-blockquote-alert.html
- hugo/package-lock.json
Improves the blockquote alerts. 
Fixes the "all-green" style that occurs after https://github.com/gardener/website-generator/issues/222
```improvement operator
NONE
```
> Improve blockquote alerts

- Dockerfile
- README.md
- compose.yaml
- hugo/config.toml
This PR allows developers to locally run the web server using docker compose
Part of https://github.com/gardener/website-generator/issues/238
```improvement operator
NONE
```
> [Docker] Running web server using docker compose

- Dockerfile
```improvement operator
NONE
```
> Rename to WEBSITE_BUILD_PATH

- README.md
Fixes https://github.com/gardener/website-generator/issues/238
```improvement operator
NONE
```
> Add Hugo website dev and maintenance section

- Dockerfile
- README.md
- package.json
- bump docforge to `v0.51.0`
- use `ARG` instead of `ENV`
- add `package.json`
- remove `WORKDIR /hugo`
- improve `CMD`
- improve `README.md`
```improvement operator
NONE
```
> Final form 

- .gitignore
This PR adds `.yaml` files to `gitignore`. This is needed when switching from docker branch to main branch those files to remain ignored
```improvement operator
NONE
```
> Don't track yaml files 

- .ci/pipeline_definitions
```improvement operator
NONE
```
> Add release job

- Dockerfile
- package.json
```improvement operator
NONE
```
> Use `Dockerfile` from docker branch

- Dockerfile
Updating of versions.
N/A
N/A
```improvement operator
NONE
```
> Update `Hugo` and `Docforge` versions

- hugo/layouts/community/list.html
Same file as `docs/list.html`
```improvement operator
NONE
```
> Add community list.html

- hugo/assets/sass/_base.scss
Fixes height problem in sidebars.
Part of https://github.com/gardener/documentation/issues/574
N/A
```improvement operator
NONE
```
> Fix navbar cutting off sidebars

- hugo/layouts/shortcodes/community-bio.html
Fixes YouTube link in community bio section.
N/A
NONE
```improvement operator
NONE
```
> Fix YouTube link in community

- hugo/assets/sass/_base.scss
Cleans up the css for the area around the logo in the Community bio section.
Fixes #275 
N/A
```improvement operator
NONE
```
> Clean up logo on community page

- Dockerfile
Updates Docforge version.
N/A
N/A
```improvement operator
Version of Docforge used for website builds is updated to v0.54.0.
```
> Update Docforge version to 0.54.0

- Dockerfile
Updates Docforge version.
N/A
N/A
```improvement operator
Version of Docforge used for website builds is updated to v0.55.0.
```
> Update Docforge version

- .ci/build
Update build script to use dir name
N/A
N/A
```improvement operator
NONE
```
> Update build script to use dir name
